env:
  - GO111MODULE=on
  - REPO=github.com/cxjava/AriaNg-go

before:
  hooks:
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
      - -X "{{.Env.REPO}}/cmd.Version={{.Version}}"
      - -X "{{.Env.REPO}}/cmd.Commit={{.FullCommit}}"
      - -X "{{.Env.REPO}}/cmd.RepoUrl={{.GitURL}}"
      - -X "{{.Env.REPO}}/cmd.BuildDate={{.Date}}"
      - -X "{{.Env.REPO}}/cmd.BuiltWithGoVersion={{.Env.GOLANG_VERSION}}"
      - -X "{{.Env.REPO}}/cmd.BuiltBy={{.Env.BUILT_BY}}"
    flags:
      - -tags=release
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - format: gz
    files:
      - none*
    replacements:
      darwin: mac
    format_overrides:
      - goos: windows
        format: zip
